/*TABELA CLIENTES*/
CREATE TABLE CLIENTES(
	ID_CLIENTE INT,
	NOME VARCHAR(30),
	IDADE INT,
	GENERO CHAR(1),
	TELEFONE VARCHAR(30),
	LOCALIZACAO VARCHAR(30)
);

COPY CLIENTES 
FROM 'C:\PROJETOS\analise_vendas\dados_clientes.csv' 
DELIMITER ',' 
CSV HEADER;

/*TABELA PRODUTOS*/
CREATE TABLE PRODUTOS(
	ID_PRODUTO INT,
	TIPO_PRODUTO VARCHAR(20),
	CATEGORIA_PRODUTO VARCHAR(20),
	TAMANHO_PRODUTO CHAR(1),
	PRECO_PRODUTO INT
);

COPY PRODUTOS 
FROM 'C:\PROJETOS\analise_vendas\dados_produtos.csv' 
DELIMITER ',' 
CSV HEADER;

/*TABELA VENDAS*/
CREATE TABLE VENDAS(
	ID_CLIENTE INT,
	ID_PRODUTO INT,
	QUANTIDADE_VENDIDA INT,
	DATA_VENDA DATE
);

COPY VENDAS
FROM 'C:\PROJETOS\analise_vendas\dados_vendas.csv' 
DELIMITER ',' 
CSV HEADER;

/*DELETAR COLUNA TAMANHO DA TABELEA PRODUTO*/
ALTER TABLE PRODUTOS
DROP COLUMN TAMANHO_PRODUTO;

/*VISUALIZAÇÃO DA TABELA CLIENTES*/
SELECT * FROM CLIENTES;
SELECT COUNT(*) AS TOTAL_CLIENTES
FROM CLIENTES; /* TOTAL = 3000 */

/*VISUALIZAÇÃO DA TABELA PRODUTOS*/
SELECT * FROM PRODUTOS;
SELECT COUNT(*) FROM PRODUTOS; /* TOTAL = 500*/

/*VISUALIZAÇÃO DA TABELA VENDAS*/
SELECT * FROM VENDAS;
SELECT COUNT(*) FROM VENDAS; /* TOTAL = 5000*/

/*APARENTEMENTE NÃO É NECESSÁRIO REALIZAR O TRATAMENTO E LIMPEZA DOS DADOS*/

/*ANÁLISE EXPLORATÓRIA DA TABELA CLIENTES*/

/* --------------------------IDADE-------------------- */
/* MIN, MÁX, MÉDIA*/
SELECT MIN(IDADE), MAX(IDADE), 
	ROUND(AVG(IDADE)) AS media_idade
FROM CLIENTES; /*MÉDIA = 51*/

/*MODA*/
SELECT IDADE, COUNT (*) AS QUANTIDADE
FROM CLIENTES
GROUP BY IDADE
ORDER BY 2 DESC /*MODA = 24*/

/*MEDIANA*/

/*FUNÇÃO PARA CALCULAR A MEDIANA*/
CREATE OR REPLACE FUNCTION _final_median(NUMERIC[])
   RETURNS NUMERIC AS
$$
   SELECT AVG(val)
   FROM (
     SELECT val
     FROM unnest($1) val
     ORDER BY 1
     LIMIT  2 - MOD(array_upper($1, 1), 2)
     OFFSET CEIL(array_upper($1, 1) / 2.0) - 1
   ) sub;
$$
LANGUAGE 'sql' IMMUTABLE;
							 
CREATE AGGREGATE median(NUMERIC) (
  SFUNC=array_append,
  STYPE=NUMERIC[],
  FINALFUNC=_final_median,
  INITCOND='{}'
);
														 
SELECT ROUND(MEDIAN(IDADE)) AS MEDIANA
FROM CLIENTES; /*MEDIANA = 50*/

/*FAIXA ETÁRIA*/
SELECT 
	CASE
		WHEN IDADE BETWEEN 18 AND 28 THEN '18-28'
		WHEN IDADE BETWEEN 29 AND 39 THEN '29-39'
		WHEN IDADE BETWEEN 40 AND 50 THEN '40-50'
		WHEN IDADE BETWEEN 51 AND 61 THEN '51-61'
		WHEN IDADE BETWEEN 62 AND 72 THEN '62-72'
		ELSE '73+'
	END AS FAIXA_ETARIA,
	COUNT(*) AS TOTAL
FROM CLIENTES
GROUP BY FAIXA_ETARIA
ORDER BY 2 DESC;

/* -----------------------GENERO---------------------- */
SELECT GENERO, COUNT(*) AS quantidade
FROM CLIENTES
GROUP BY GENERO;

/* -----------------------LOCALIZACAO---------------------- */
SELECT LOCALIZACAO, COUNT(*) AS quantidade
FROM CLIENTES
GROUP BY LOCALIZACAO
ORDER BY 2 DESC;

/*----------IDADE, GENERO, LOCALIZACAO-----------------------*/
/*ONDE HÁ MAIS CLIENTES DO SEXO MASCULINO*/
SELECT LOCALIZACAO, COUNT(*) AS TOTAL
FROM CLIENTES
WHERE GENERO ='M'
GROUP BY LOCALIZACAO
ORDER BY 2 DESC;

/*FAIXA ETÁRIA RIO DE JANEIRO*/
SELECT 
	CASE
		WHEN IDADE BETWEEN 18 AND 28 THEN '18-28'
		WHEN IDADE BETWEEN 29 AND 39 THEN '29-39'
		WHEN IDADE BETWEEN 40 AND 50 THEN '40-50'
		WHEN IDADE BETWEEN 51 AND 61 THEN '51-61'
		WHEN IDADE BETWEEN 62 AND 72 THEN '62-72'
		ELSE '73+'
	END AS FAIXA_ETARIA,
	COUNT(*) AS TOTAL
FROM CLIENTES
WHERE LOCALIZACAO = 'Rio de Janeiro'
GROUP BY FAIXA_ETARIA
ORDER BY 2 DESC;

/*FAIXA ETÁRIA BELO HORIZONTE*/
SELECT 
	CASE
		WHEN IDADE BETWEEN 18 AND 28 THEN '18-28'
		WHEN IDADE BETWEEN 29 AND 39 THEN '29-39'
		WHEN IDADE BETWEEN 40 AND 50 THEN '40-50'
		WHEN IDADE BETWEEN 51 AND 61 THEN '51-61'
		WHEN IDADE BETWEEN 62 AND 72 THEN '62-72'
		ELSE '73+'
	END AS FAIXA_ETARIA,
	COUNT(*) AS TOTAL
FROM CLIENTES
WHERE LOCALIZACAO = 'Belo Horizonte'
GROUP BY FAIXA_ETARIA
ORDER BY 2 DESC;

/*FAIXA ETÁRIA CURITIBA*/
SELECT 
	CASE
		WHEN IDADE BETWEEN 18 AND 28 THEN '18-28'
		WHEN IDADE BETWEEN 29 AND 39 THEN '29-39'
		WHEN IDADE BETWEEN 40 AND 50 THEN '40-50'
		WHEN IDADE BETWEEN 51 AND 61 THEN '51-61'
		WHEN IDADE BETWEEN 62 AND 72 THEN '62-72'
		ELSE '73+'
	END AS FAIXA_ETARIA,
	COUNT(*) AS TOTAL
FROM CLIENTES
WHERE LOCALIZACAO = 'Curitiba'
GROUP BY FAIXA_ETARIA
ORDER BY 2 DESC;

/*FAIXA ETÁRIA SÃO PAULO*/
SELECT 
	CASE
		WHEN IDADE BETWEEN 18 AND 28 THEN '18-28'
		WHEN IDADE BETWEEN 29 AND 39 THEN '29-39'
		WHEN IDADE BETWEEN 40 AND 50 THEN '40-50'
		WHEN IDADE BETWEEN 51 AND 61 THEN '51-61'
		WHEN IDADE BETWEEN 62 AND 72 THEN '62-72'
		ELSE '73+'
	END AS FAIXA_ETARIA,
	COUNT(*) AS TOTAL
FROM CLIENTES
WHERE LOCALIZACAO = 'São Paulo'
GROUP BY FAIXA_ETARIA
ORDER BY 2 DESC;

/*FAIXA ETÁRIA SALVADOR*/
SELECT 
	CASE
		WHEN IDADE BETWEEN 18 AND 28 THEN '18-28'
		WHEN IDADE BETWEEN 29 AND 39 THEN '29-39'
		WHEN IDADE BETWEEN 40 AND 50 THEN '40-50'
		WHEN IDADE BETWEEN 51 AND 61 THEN '51-61'
		WHEN IDADE BETWEEN 62 AND 72 THEN '62-72'
		ELSE '73+'
	END AS FAIXA_ETARIA,
	COUNT(*) AS TOTAL
FROM CLIENTES
WHERE LOCALIZACAO = 'Salvador'
GROUP BY FAIXA_ETARIA
ORDER BY 2 DESC;



/* ************************************** ANÁLISE TABELA PRODUTOS *************************************** */
/* -----------------------TIPO DE PRODUTO---------------------- */
SELECT TIPO_PRODUTO, COUNT(*) AS QUANTIDADE
FROM PRODUTOS
GROUP BY TIPO_PRODUTO
ORDER BY 2;

/* -----------------------CATEGORIA PRODUTO---------------------- */
SELECT CATEGORIA_PRODUTO, COUNT(*) AS QUANTIDADE
FROM PRODUTOS
GROUP BY CATEGORIA_PRODUTO
ORDER BY 2;

/*----------------------PREÇO DO PRODUTO-------------*/

/*VALORES MÉDIO, MÁXIMO E MÍNIMO*/
SELECT 
	MAX(PRECO_PRODUTO) AS MAXIMO, 
	MIN(PRECO_PRODUTO) AS MINIMO,
	ROUND(AVG(PRECO_PRODUTO)) AS MEDIA_PRECO
FROM PRODUTOS;

/*MODA*/
SELECT PRECO_PRODUTO, COUNT (*) AS QUANTIDADE
FROM PRODUTOS
GROUP BY PRECO_PRODUTO
ORDER BY 2 DESC; /*MODA = 208*/

/*MEDIANA*/
														 
SELECT ROUND(MEDIAN(PRECO_PRODUTO)) AS MEDIANA
FROM PRODUTOS; /*MEDIANA = 169*/

/*PRECO MEDIO, MÁXIMO E MÍNIMO POR TIPO DE PRODUTO*/
SELECT 
	TIPO_PRODUTO, 
	MAX(PRECO_PRODUTO) AS MAXIMO, 
	MIN(PRECO_PRODUTO) AS MINIMO,
	ROUND(AVG(PRECO_PRODUTO)) AS MEDIA_PRECO
FROM PRODUTOS
GROUP BY TIPO_PRODUTO;

/*PRECO MEDIO, MÁXIMO E MÍNIMO POR CATEGORIA DE PRODUTO*/
SELECT 
	CATEGORIA_PRODUTO,
	MAX(PRECO_PRODUTO) AS MAXIMO, 
	MIN(PRECO_PRODUTO) AS MINIMO,
	ROUND(AVG(PRECO_PRODUTO)) AS MEDIA_PRECO
FROM PRODUTOS
GROUP BY CATEGORIA_PRODUTO;

/*PRECO MEDIO, MÁXIMO E MÍNIMO POR CATEGORIA DE PRODUTO E TIPO DE PRODUTO*/
SELECT 
	TIPO_PRODUTO,
	CATEGORIA_PRODUTO,
	MAX(PRECO_PRODUTO) AS MAXIMO, 
	MIN(PRECO_PRODUTO) AS MINIMO,
	ROUND(AVG(PRECO_PRODUTO)) AS MEDIA_PRECO
FROM PRODUTOS
GROUP BY TIPO_PRODUTO, CATEGORIA_PRODUTO
ORDER BY TIPO_PRODUTO, CATEGORIA_PRODUTO;

/*PRODUTOS POR FAIXA DE PRECO*/

SELECT TIPO_PRODUTO, CATEGORIA_PRODUTO, 
	COUNT(CASE WHEN PRECO_PRODUTO BETWEEN 49 AND 99 THEN 1 ELSE NULL END) AS "49-99",
	COUNT(CASE WHEN PRECO_PRODUTO BETWEEN 100 AND 150 THEN 1 ELSE NULL END) AS "100-150",
	COUNT(CASE WHEN PRECO_PRODUTO BETWEEN 151 AND 200 THEN 1 ELSE NULL END) AS "151-200",
	COUNT(CASE WHEN PRECO_PRODUTO BETWEEN 201 AND 250 THEN 1 ELSE NULL END) AS "201-250",
	COUNT(CASE WHEN PRECO_PRODUTO > 250 THEN 1 ELSE NULL END) AS "250+"
FROM PRODUTOS
GROUP BY TIPO_PRODUTO, CATEGORIA_PRODUTO
ORDER BY 1,2;

/*-----------------********************************ANÁLISE TABELA VENDAS****************************---------------------------*/
SELECT COUNT(*) AS TOTAL_VENDAS
FROM VENDAS;

SELECT COUNT(DISTINCT ID_CLIENTE)
FROM VENDAS;

/*VENDAS POR MÊS*/
SELECT EXTRACT (MONTH FROM DATA_VENDA) AS MES, COUNT (*) AS TOTAL_VENDAS
FROM VENDAS
GROUP BY MES
ORDER BY 2 DESC;

SELECT TO_CHAR(DATA_VENDA,'MONTH') AS MES,
COUNT (*) AS TOTAL_VENDAS
FROM VENDAS
GROUP BY MES
ORDER BY MIN(DATA_VENDA);

/*-------------***************************ANALISE COMBINATORIA DAS TABELAS*********************************-------------------*/

/*VALOR GASTO POR MULHERES EM CADA TIPO DE ITEM*/
SELECT  
	P.TIPO_PRODUTO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.GENERO = 'F'
GROUP BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO
ORDER BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO, TOTAL_GASTO DESC;

/*VALOR GASTO POR HOMENS EM CADA TIPO DE ITEM*/
SELECT  
	P.TIPO_PRODUTO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.GENERO = 'M'
GROUP BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO
ORDER BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO, TOTAL_GASTO DESC;

SELECT C.LOCALIZACAO, SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
GROUP BY C.LOCALIZACAO
ORDER BY TOTAL_GASTO DESC;

/*------------------TIPO DE PRODUTO VENDIDO POR CIDADE---------------------------*/
/*BELO HORIZONTE*/
SELECT 
	P.TIPO_PRODUTO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.LOCALIZACAO = 'Belo Horizonte'
GROUP BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO
ORDER BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO, TOTAL_GASTO DESC;

/*RIO DE JANEIRO*/
SELECT 
	P.TIPO_PRODUTO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.LOCALIZACAO = 'Rio de Janeiro'
GROUP BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO
ORDER BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO, TOTAL_GASTO DESC;

/*SÃO PAULO*/
SELECT 
	P.TIPO_PRODUTO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.LOCALIZACAO = 'São Paulo'
GROUP BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO
ORDER BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO, TOTAL_GASTO DESC;

/*SALVADOR*/
SELECT 
	P.TIPO_PRODUTO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.LOCALIZACAO = 'Salvador'
GROUP BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO
ORDER BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO, TOTAL_GASTO DESC;

/*CURITIBA*/
SELECT 
	P.TIPO_PRODUTO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.LOCALIZACAO = 'Curitiba'
GROUP BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO
ORDER BY P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO, TOTAL_GASTO DESC;

/*
SELECT 
	CASE
		WHEN C.IDADE BETWEEN 18 AND 28 THEN '18-28'
		WHEN C.IDADE BETWEEN 29 AND 39 THEN '29-39'
		WHEN C.IDADE BETWEEN 40 AND 50 THEN '40-50'
		WHEN C.IDADE BETWEEN 51 AND 61 THEN '51-61'
		ELSE '62+'
	END,
	P.TIPO_PRODUTO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
GROUP BY C.IDADE, P.TIPO_PRODUTO, P.CATEGORIA_PRODUTO
ORDER BY C.IDADE, TOTAL_GASTO DESC;
*/

/*VENDA DE PRODUTO RELACIONANDO FAIXA ETÁRIA E LOCAL*/
/*Salvador*/
SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 18 AND 28 AND C.LOCALIZACAO = 'Salvador'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 29 AND 39 AND C.LOCALIZACAO = 'Salvador'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 40 AND 50 AND C.LOCALIZACAO = 'Salvador'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 51 AND 61 AND C.LOCALIZACAO = 'Salvador'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE >=62 AND C.LOCALIZACAO = 'Salvador'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*Belo Horizonte*/
SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 18 AND 28 AND C.LOCALIZACAO = 'Belo Horizonte'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 29 AND 39 AND C.LOCALIZACAO = 'Belo Horizonte'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 40 AND 50 AND C.LOCALIZACAO = 'Belo Horizonte'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 51 AND 61 AND C.LOCALIZACAO = 'Belo Horizonte'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE >=62 AND C.LOCALIZACAO = 'Belo Horizonte'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

/*Rio de Janeiro*/

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 18 AND 28 AND C.LOCALIZACAO = 'Rio de Janeiro'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 29 AND 39 AND C.LOCALIZACAO = 'Rio de Janeiro'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 40 AND 50 AND C.LOCALIZACAO = 'Rio de Janeiro'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 51 AND 61 AND C.LOCALIZACAO = 'Rio de Janeiro'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE >=62 AND C.LOCALIZACAO = 'Rio de Janeiro'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

/*Curitiba*/

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 18 AND 28 AND C.LOCALIZACAO = 'Curitiba'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 29 AND 39 AND C.LOCALIZACAO = 'Curitiba'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 40 AND 50 AND C.LOCALIZACAO = 'Curitiba'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 51 AND 61 AND C.LOCALIZACAO = 'Curitiba'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE >=62 AND C.LOCALIZACAO = 'Curitiba'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

/*São Paulo*/

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 18 AND 28 AND C.LOCALIZACAO = 'São Paulo'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 29 AND 39 AND C.LOCALIZACAO = 'São Paulo'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 40 AND 50 AND C.LOCALIZACAO = 'São Paulo'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 51 AND 61 AND C.LOCALIZACAO = 'São Paulo'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

SELECT 
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE >=62 AND C.LOCALIZACAO = 'São Paulo'
GROUP BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO, TOTAL_GASTO DESC;

/*

/*ACESSORIOS*/
SELECT 
	C.LOCALIZACAO,
	P.TIPO_PRODUTO,
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 18 AND 28 AND P.TIPO_PRODUTO = 'Acessórios'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO, P.TIPO_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*CALÇADOS*/
SELECT 
	C.LOCALIZACAO,  
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 18 AND 28 AND P.TIPO_PRODUTO = 'Calçados'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*ROUPAS*/
SELECT 
	C.LOCALIZACAO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 29 AND 39 AND TIPO_PRODUTO = 'Roupas'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*ACESSORIOS*/
SELECT 
	C.LOCALIZACAO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 29 AND 39 AND TIPO_PRODUTO = 'Acessórios'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*CALCADOS*/
SELECT 
	C.LOCALIZACAO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 29 AND 39 AND TIPO_PRODUTO = 'Calçados'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*ROUPAS*/
SELECT 
	C.LOCALIZACAO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 40 AND 50 AND TIPO_PRODUTO = 'Roupas'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*ACESSORIOS*/
SELECT 
	C.LOCALIZACAO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 40 AND 50 AND TIPO_PRODUTO = 'Acessórios'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*CALCADOS*/
SELECT 
	C.LOCALIZACAO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 40 AND 50 AND TIPO_PRODUTO = 'Calçados'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;


/*ROUPAS*/
SELECT 
	C.LOCALIZACAO,  
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 51 AND 61 AND TIPO_PRODUTO = 'Roupas'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*ACESSORIOS*/
SELECT 
	C.LOCALIZACAO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 51 AND 61 AND TIPO_PRODUTO = 'Acessórios'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*CALCADOS*/
SELECT 
	C.LOCALIZACAO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE BETWEEN 51 AND 61 AND TIPO_PRODUTO = 'Calçados'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*ROUPAS*/
SELECT 
	C.LOCALIZACAO,  
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE >= 62 AND TIPO_PRODUTO = 'Roupas'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*ACESSORIOS*/
SELECT 
	C.LOCALIZACAO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE >= 62 AND TIPO_PRODUTO = 'Acessórios'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;

/*CALCADOS*/
SELECT 
	C.LOCALIZACAO, 
	P.CATEGORIA_PRODUTO,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
WHERE C.IDADE >= 62 AND TIPO_PRODUTO = 'Calçados'
GROUP BY C.LOCALIZACAO, P.CATEGORIA_PRODUTO
ORDER BY C.LOCALIZACAO, TOTAL_GASTO DESC;*/

/*VALOR DAS VENDAS POR MÊS*/
SELECT 
	TO_CHAR(V.DATA_VENDA,'MONTH') AS MES,
	SUM(V.QUANTIDADE_VENDIDA * P.PRECO_PRODUTO) AS TOTAL_GASTO
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
GROUP BY MES
ORDER BY TOTAL_GASTO DESC;

SELECT
	TO_CHAR(V.DATA_VENDA,'MONTH') AS MES,
	P.CATEGORIA_PRODUTO,
	COUNT (CASE WHEN P.TIPO_PRODUTO = 'Roupas' THEN 1 ELSE NULL END) AS roupas,
	COUNT (CASE WHEN P.TIPO_PRODUTO = 'Acessórios' THEN 1 ELSE NULL END) AS acessorios,
	COUNT (CASE WHEN P.TIPO_PRODUTO = 'Calçados' THEN 1 ELSE NULL END) AS calcados
FROM VENDAS V 
JOIN CLIENTES C
ON V.ID_CLIENTE = C.ID_CLIENTE
JOIN PRODUTOS P
ON V.ID_PRODUTO = P.ID_PRODUTO
GROUP BY P.CATEGORIA_PRODUTO, MES
ORDER BY MIN(DATA_VENDA), P.CATEGORIA_PRODUTO;



